### ISSUE TITLE
TORE GWD computation is very slow

### ISSUE THREAD

**Issue by looper99** [uzh-rpg/event_representation_study#2]
Hi authors, nice paper!

I was able to reproduce experiments for GWD and optimization and also evaluate networks on both datasets on all representations except TORE.

Is there any plan to update repo with faster TORE implementation?

**Comment by Vayne0227** [comment]
Hi, have you ever encountered a scenario where the event representation is set as "TimeSurface," but the "chosen_time_surface" is directly equal to"chosen"? I noticed that when I attempted this, the GWD value of the TimeSurface was approximately 0.5, which differs from the value mentioned by the author in the paper. I would appreciate your guidance on any specific details I might have overlooked in order to better understand the situation. This is the detail I modified.
![8814003aa972b00c0a2e958a38ea344](https://github.com/uzh-rpg/event_representation_study/assets/66624169/e0af2656-5956-424f-b723-15767109cdce)

**Comment by NikolaZubic** [comment]
@Vayne0227 Make sure you have the same environment installation and seeds as we had, also do not change the code, and it should be the same/similar, at least the ordering.

@looper99 regarding the TORE representation, it was not optimized as we just wanted to compare how it performs in terms of mAP - GWD correlation. Since it was not the best-performing representation, we did not invest time optimizing it.

I just took MATLAB code and wrote Python script as fast as possible. We do not have a plan to write a more optimized version of TORE as it was not the main focus of the paper.
